//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothingMain
    {
        public int ClothingID { get; set; }
        public int TopsID { get; set; }
        public int BottomsID { get; set; }
        public int ShoesID { get; set; }
        public int AccessoriesID { get; set; }
    
        public virtual AccessoriesStuff AccessoriesStuff { get; set; }
        public virtual BottomStuff BottomStuff { get; set; }
        public virtual ShoeStuff ShoeStuff { get; set; }
        public virtual TopStuff TopStuff { get; set; }
    }
}
